language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t mmzaki/client-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true mmzaki/client-test npm run test -- --coverage

after_success:
    - docker build -t mmzaki/client-aws ./client
    - docker build -t mmzaki/nginx-aws ./nginx
    - docker build -t mmzaki/subscriber-aws ./subscriber
    - docker build -t mmzaki/worker-aws ./worker

    # login to docker hub before pushing the images
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push mmzaki/client-aws
    - docker push mmzaki/nginx-aws
    - docker push mmzaki/subscriber-aws
    - docker push mmzaki/worker-aws

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-875906334048"
    bucket_path: "multi-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
