version: "3"
services:
    redis:
        image: "redis:latest"
    worker:
        build:
            context: ./worker
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./worker:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    subscriber:
        build:
            context: ./subscriber
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./subscriber:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
