version: "3"
services:
    redis:
        image: "redis:latest"
    postgress:
        image: "postgres"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
    customer:
        depends_on:
            - "postgress"
        build:
            context: ./customer
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./customer:/app
        ports:
            - "5000:5000"
        environment:
            - CUSTOMER_PG_USER=postgres
            - CUSTOMER_PG_HOST=postgres
            - CUSTOMER_PG_DB=postgres
            - CUSTOMER_PG_PASS=postgres
            - CUSTOMER_PG_PORT=5432
    nginx:
        depends_on:
            - subscriber
            - client
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
            - "3050:80"
    worker:
        build:
            context: ./worker
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./worker:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./client:/app
    subscriber:
        build:
            context: ./subscriber
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./subscriber:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
